### ISSUE TITLE
build fails due to /etc/ssh not existing

### ISSUE THREAD

**Issue by lotek4u** [onemarcfifty/kali-linux-docker#2]
Not able to build the file as is. Looks like the Dockerfile is missing the command to create that directory, so it can't be echoed into.

**Comment by lotek4u** [comment]
I fixed it by putting this on line 101 of the Dockerfile

RUN mkdir -p /etc/ssh

I don't know how to do a pull request, i tried and it looked like i "couldn't" so just putting it here.

**Comment by onemarcfifty** [comment]
Hi, this is presumably because sshd is not installed by default. I'll have a look into that.

**Comment by onemarcfifty** [comment]
Should be fixed by the latest commit. Please try pulling again (git pull or git clone)

**Comment by lotek4u** [comment]
Thanks. It does build. I can exec in as root with /bin/bash  but can't ssh into the container, even after changing the password with root from exec. Haven't figured it out yet.

**Comment by onemarcfifty** [comment]
Please keep in mind that the ssh port defaults to 20022 - you would have to ssh with the `-p 20022` argument.

**Comment by onemarcfifty** [comment]
You can change that in the build script
